# Change these first
owner: bittybyte-au # Your GitHub organization or username, where this repository lives
repo: site-monitoring # The name of this repository

sites:
  - name: Your Chief AI Officer
    url: https://yourchiefaiofficer.ai
  - name: evince Consulting
    url: https://evince.com.au
  - name: BittyByte
    url: https://bittybyte.com.au
  - name: Amit Singh
    url: https://amits.com.au
  - name: BST Joinery
    url: https://bstjoinery.com.au
  - name: NextEra Bookkeeping
    url: https://nexterabookkeeping.com.au 
  - name: Guided Growth
    url: https://guidedgrowth.com.au 
  - name: Talent Journey
    url: https://talentjourney.com.au 
  - name: Capital Lift Finance
    url: https://capitallift.com.au     
  - name: Carmen Rossitto
    url: https://carmenrossitto.com
  - name: Moss & Tide Homes
    url: https://mossandtide.com.au   
  - name: Mind & heart Grief Counselling
    url: https://mindandheartgriefcounselling.com.au
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /site-monitoring
  logoUrl: assets/bb-logo-icon.svg
  name: Site Monitoring
  introTitle: "**Site Monitoring**"
  introMessage: This is a status page to monitor uptime for BittyByte websites.
  faviconSvg: assets/favicon.svg
  i18n:
    footer: [http://bittybyte.com.au](http://bittybyte.com.au)
  navbar:
    - title: Docs
      href: https://upptime.js.org/docs/
    - title: Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
