# Change these first
owner: bittybyte-au
repo: site-monitoring

skipDeleteIssues: true
delay: 2000

workflowSchedule:
  uptime: "*/10 * * * *"

sites:
  - name: Your Chief AI Officer
    url: https://yourchiefaiofficer.ai
  - name: evince Consulting
    url: https://evince.ai
  - name: BittyByte
    url: https://bittybyte.com.au
  - name: Amit Singh
    url: https://amits.com.au
  - name: BST Joinery
    url: https://bstjoinery.com.au
  - name: NextEra Bookkeeping
    url: https://nexterabookkeeping.com.au
  - name: Guided Growth
    url: https://guidedgrowth.com.au
  - name: Talent Journey
    url: https://talentjourney.com.au
  - name: Capital Lift Finance
    url: https://capitallift.com.au
  - name: Carmen Rossitto
    url: https://carmenrossitto.com
  - name: Moss & Tide Homes
    url: https://mossandtide.com.au
  - name: Mind & Heart Grief Counselling
    url: https://mindandheartgriefcounselling.com.au

status-website:
  baseUrl: /site-monitoring
  logoUrl: https://bittybyte-au.github.io/site-monitoring/bb-icon.png
  name: Site Monitoring
  introTitle: "**Site Monitoring**"
  introMessage: This is a status page to monitor uptime for BittyByte websites.
  faviconSvg: https://bittybyte-au.github.io/site-monitoring/favicon.svg
  navbar:
    - title: Docs
      href: https://upptime.js.org/docs/
    - title: Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
